services:
  web:
    build: .
    container_name: solar_web
    ports:
      - "8000:8000"
    environment:
      - DEBUG=False
      - SECRET_KEY=ch@ng3-th1s-t0-a-r34l-s3cr3t-k3y-in-pr0duct10n
      - ALLOWED_HOSTS=*
      - CORS_ALLOWED_ORIGINS=http://localhost:8000
      - CSRF_TRUSTED_ORIGINS=http://localhost:8000
      - DJANGO_VITE_DEV_MODE=False
    restart: unless-stopped
    volumes:
      - app_data:/app/db
      - media_data:/app/media

volumes:
  app_data:
  media_data:
