# Generated by Django 6.0 on 2026-02-22 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(choices=[('project_type', 'Project Type'), ('lead_priority', 'Lead Priority'), ('lead_source', 'Lead Source')], max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['group', 'order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='lead',
            name='is_converted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(default='contact_form', max_length=50),
        ),
        migrations.AddField(
            model_name='lead',
            name='category',
            field=models.ForeignKey(blank=True, limit_choices_to={'group': 'project_type'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='CRM.category'),
        ),
        migrations.AddField(
            model_name='lead',
            name='priority',
            field=models.ForeignKey(blank=True, limit_choices_to={'group': 'lead_priority'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='priority_leads', to='CRM.category'),
        ),
    ]
